import {cms} from '@/cms'
import 'alinea/css'
import {PropsWithChildren} from 'react'
import '../styles/global.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        {children}
        <cms.previews />
      </body>
    </html>
  )
}
