logFilters:
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs
