export enum HandleAction {
  Auth = 'auth',
  Capabilities = 'capabilities',
  User = 'user',
  Resolve = 'resolve',
  ReplicaBootstrap = 'replicaBootstrap',
  ReplicaState = 'replicaState',
  ReplicaObject = 'replicaObject',
  ReplicaMutate = 'replicaMutate',
  ReplicaCommand = 'replicaCommand',
  ReplicaBundle = 'replicaBundle',
  ReplicaEligible = 'replicaEligible',
  Pending = 'pending',
  Sync = 'sync',
  Draft = 'draft',
  History = 'history',
  PreviewToken = 'previewToken',
  Mutate = 'mutate',
  Upload = 'upload',
  Tree = 'tree',
  Commit = 'commit',
  Blob = 'blob'
}
