import fs from 'node:fs/promises'
import path from 'node:path'
import {createId} from 'alinea/core/Id'
import {MemorySource} from 'alinea/core/source/MemorySource'
import {exportSource} from 'alinea/core/source/SourceExport'
import {writeFileIfContentsDiffer} from '../util/FS.js'
import type {GenerateContext} from './GenerateContext.js'

const packageJson = {
  private: true,
  version: '0.0.0',
  name: '@alinea/generated',
  type: 'module',
  sideEffects: false,
  exports: {
    './package.json': './package.json',
    './config.js': './config.js',
    './release.js': './release.js',
    './source.js': {
      'edge-light': './empty-source.js',
      default: './source.js'
    }
  }
}

const emptySource = await exportSource(new MemorySource())

export async function copyStaticFiles({outDir}: GenerateContext) {
  await fs.mkdir(outDir, {recursive: true}).catch(console.error)

  await fs.writeFile(
    path.join(outDir, 'release.js'),
    `export const release = ${JSON.stringify(createId())}`
  )
  await fs.writeFile(
    path.join(outDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  )
  await fs.writeFile(
    path.join(outDir, 'empty-source.js'),
    `export const source = ${JSON.stringify(emptySource, null, 2)}`
  )
  await fs.writeFile(
    path.join(outDir, 'source.js'),
    `export const source = ${JSON.stringify(emptySource, null, 2)}`
  )
  // await writeFileIfContentsDiffer(path.join(outDir, '.gitignore'), `*\n!.keep`)*/
  await writeFileIfContentsDiffer(
    path.join(outDir, '.keep'),
    '# Contents of this folder are autogenerated by alinea'
  )
}
