import fs from 'fs-extra'
import path from 'node:path'
import {writeFileIfContentsDiffer} from '../util/FS.js'
import {GenerateContext} from './GenerateContext.js'

const packageJson = {
  private: true,
  version: '0.0.0',
  name: '@alinea/content',
  type: 'module',
  sideEffects: false,
  exports: {
    './*': './*'
  }
}

export async function copyStaticFiles({staticDir, outDir}: GenerateContext) {
  await fs.mkdirp(outDir).catch(console.log)
  function copy(...files: Array<string>) {
    return Promise.all(
      files.map(file =>
        fs.copyFile(path.join(staticDir, file), path.join(outDir, file))
      )
    )
  }
  fs.writeJSONSync(path.join(outDir, 'package.json'), packageJson, {spaces: 2})
  await writeFileIfContentsDiffer(path.join(outDir, '.gitignore'), `*\n!.keep`)
  await writeFileIfContentsDiffer(
    path.join(outDir, '.keep'),
    '# Contents of this folder are autogenerated by alinea'
  )
}
