import {createId} from '#/core/Id.js'
import {generatedDatabaseFile} from '#/database/Version.js'
import fs from 'node:fs/promises'
import path from 'node:path'
import {writeFileIfContentsDiffer} from '../util/FS.js'
import type {GenerateContext} from './GenerateContext.js'

const packageJson = {
  private: true,
  version: '0.0.0',
  name: '@alinea/generated',
  type: 'module',
  sideEffects: false,
  exports: {
    './package.json': './package.json',
    './release.js': './release.js',
    './database.node.js': './database.node.js'
  }
}

export async function copyStaticFiles({
  cmd,
  packageDir,
  outDir
}: Pick<GenerateContext, 'cmd' | 'packageDir' | 'outDir'>) {
  await fs.mkdir(outDir, {recursive: true}).catch(console.error)
  await cleanupOldDatabases(outDir)

  // The runtime modules point at a single project. A build claims them for
  // its project; a dev server only creates them when missing so it cannot
  // redirect a build of another project sharing this package. Dev runtimes
  // locate their database through ALINEA_GENERATED_DATABASE instead.
  const claim = cmd === 'build'
  await writeRuntimeFile(
    path.join(packageDir, 'release.js'),
    `export const release = ${JSON.stringify(createId())}`,
    claim
  )
  // A static asset reference lets file tracing bundle the database with the
  // serverless functions that open it, wherever this package is hoisted to.
  const database = path
    .relative(packageDir, path.join(outDir, generatedDatabaseFile))
    .replace(/\\/g, '/')
  await writeRuntimeFile(
    path.join(packageDir, 'database.node.js'),
    `export const database = new URL(${JSON.stringify(`./${database}`)}, import.meta.url)`,
    claim
  )
  await writeFileIfContentsDiffer(
    path.join(packageDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  )
  await writeFileIfContentsDiffer(
    path.join(packageDir, '.keep'),
    '# Contents of this folder are autogenerated by alinea'
  )
}

async function writeRuntimeFile(
  file: string,
  contents: string,
  overwrite: boolean
) {
  if (overwrite) return fs.writeFile(file, contents)
  await fs.writeFile(file, contents, {flag: 'wx'}).catch(error => {
    if (error?.code !== 'EEXIST') throw error
  })
}

export async function cleanupOldDatabases(outDir: string): Promise<void> {
  const files = await fs.readdir(outDir).catch(() => [])
  const currentFiles = new Set([
    generatedDatabaseFile,
    `${generatedDatabaseFile}-shm`,
    `${generatedDatabaseFile}-wal`
  ])
  const oldFiles = files.filter(
    file =>
      !currentFiles.has(file) &&
      /^database(?:-.+)?\.sqlite(?:-(?:shm|wal))?$/.test(file)
  )
  await Promise.all(
    oldFiles.map(file =>
      fs.rm(path.join(outDir, file), {force: true}).catch(() => {})
    )
  )
}
