import {MemorySource} from '#/core/source/MemorySource.js'
import {type ExportedSource, importSource} from '#/core/source/SourceExport.js'

async function generatedSourceFile(): Promise<string> {
  // @ts-expect-error The package is generated by the Alinea CLI.
  const generated = await import('@alinea/generated/source.js')
  const {sourceFile}: {sourceFile: unknown} = generated
  if (typeof sourceFile !== 'string' || !sourceFile.startsWith('/'))
    throw new Error('Alinea generated source file is missing')
  return sourceFile
}

export async function fetchGeneratedSource(
  baseUrl: URL
): Promise<MemorySource> {
  try {
    const sourceFile = await generatedSourceFile()
    const response = await fetch(new URL(sourceFile, baseUrl))
    if (!response.ok)
      throw new Error(
        `Could not fetch Alinea generated source (${response.status})`
      )
    return importSource((await response.json()) as ExportedSource)
  } catch (error) {
    console.error(error)
    return new MemorySource()
  }
}
