export const viewKeys = {
  CheckInput: 'alinea/field/check/CheckField.view#CheckInput',
  CodeInput: 'alinea/field/code/CodeField.view#CodeInput',
  DateInput: 'alinea/field/date/DateField.view#DateInput',
  HiddenInput: 'alinea/field/hidden/HiddenField.view#HiddenInput',
  JsonInput: 'alinea/field/json/JsonField.view#JsonInput',
  SingleLinkInput: 'alinea/field/link/LinkField.view#SingleLinkInput',
  MultipleLinksInput: 'alinea/field/link/LinkField.view#MultipleLinksInput',
  ListInput: 'alinea/field/list/ListField.view#ListInput',
  MetadataInput: 'alinea/field/metadata/MetadataField.view#MetadataInput',
  NumberInput: 'alinea/field/number/NumberField.view#NumberInput',
  ObjectInput: 'alinea/field/object/ObjectField.view#ObjectInput',
  PathInput: 'alinea/field/path/PathField.view#PathInput',
  RichTextInput: 'alinea/field/richtext/RichTextField.view#RichTextInput',
  SelectInput: 'alinea/field/select/SelectField.view#SelectInput',
  TabsView: 'alinea/field/tabs/Tabs.view#TabsView',
  TextInput: 'alinea/field/text/TextField.view#TextInput',
  TimeInput: 'alinea/field/time/TimeField.view#TimeInput',
  MediaExplorer: 'alinea/dashboard/view/MediaExplorer#MediaExplorer',
  MediaFile: 'alinea/dashboard/view/media/FileEntry#FileEntry',
  FileSummaryRow: 'alinea/dashboard/view/media/FileSummary#FileSummaryRow',
  FileSummaryThumb: 'alinea/dashboard/view/media/FileSummary#FileSummaryThumb'
}
