// Config creation
export {createMediaRoot as media} from '#/core/media/MediaRoot.js'
export {createConfig as create} from './core/Config.js'
export {document} from './core/Document.js'
export {page} from './core/Page.js'
export {snippet} from './core/pages/Snippet.js'
export {root} from './core/Root.js'
export {schema} from './core/Schema.js'
export {track} from './core/Tracker.js'
export {type} from './core/Type.js'
export {role} from './core/Role.js'
export {workspace} from './core/Workspace.js'
